MODEL: 3                      # 1: structure model, 2: inpaint model, 3: structure-inpaint model
VERBOSE: 1                    # turns on verbose mode in the output console
GPU: [0]                      # gpu ids


MAX_ITERS: 15000000          # maximum number of iterations to train the model
LR: 0.0001                    # learning rate
BETA1: 0                      # adam optimizer beta1
BETA2: 0.999                  # adam optimizer beta2
LR_POLICY: constant           # the method to adjust learning rate (eg: constant|step)
STEP_SIZE: 10000              # Period of learning rate decay (only used when choosing "step" as the lr adjusment method)
GAMMA: 0.5                    # Multiplicative factor of learning rate decay. (only used when choosing "step" as the lr adjusment method)
INIT_TYPE: xavier             # initialization [gaussian/kaiming/xavier/orthogonal]

SAVE_INTERVAL: 10000          # how many iterations to wait before saving model
SAVE_LATEST: 1000             # how many iterations to wait before saving lastest model
SAMPLE_INTERVAL: 1000         # how many iterations to wait before sampling
SAMPLE_SIZE: 10               # number of images to sample
EVAL_INTERVAL: 1000           # how many iterations to wait before model evaluation
LOG_INTERVAL: 100             # how many iterations to wait before logging training status 
WHICH_ITER: latest            # which iterations to load

DIS_GAN_LOSS: lsgan           # type of gan loss

STRUCTURE_L1: 5               # structure net parameter of l1 loss
STRUCTURE_ADV_GEN: 1          # structure net parameter of gan loss  

FLOW_ADV_GEN: 1               # texture net parameter of gan loss  
FLOW_L1: 5                    # texture net parameter of l1 loss
FLOW_CORRECTNESS: 0.25        # structure net parameter of sampling correctness loss
VGG_STYLE: 250                # parameter of vgg_style loss
VGG_CONTENT: 0.1              # parameter of vgg_content loss


TRAIN_BATCH_SIZE: 6           # batch size
DATA_TRAIN_SIZE: 256          # image size for training 
DATA_TEST_SIZE: 256           # image size for testing (False for never resize)
DATA_FLIP: False              # filp image or not when training 
DATA_CROP: FALSE #[537,537]   # crop size when training (False for never cro)
DATA_MASK_TYPE: from_file     # mask type (random_bbox|random_free_form|from_file)
DATA_RANDOM_BBOX_SETTING:     # parameters for random_bbox
  random_size: False          # random hole size according to shape [0.4*shape shape]
  shape: [80, 80]             # hole size
  margin: [0, 0]              # minimum distance from the image boundary
  num: 1
DATA_RANDOM_FF_SETTING:       # parameters for random_free_form
  mv: 10
  ma: 4.0
  ml: 60
  mbw: 15


# use Pairs dataset
DATA_TRAIN_GT: ./pair_train_gt.txt
DATA_TRAIN_STRUCTURE: ./pairs_train_sm.txt
DATA_VAL_GT: ./paris_eval_gt.txt
DATA_VAL_STRUCTURE: ./paris_eval_sm.txt
DATA_VAL_MASK: ./val_mask_dataset.txt
DATA_MASK_FILE:  #parameters for from_file


